services:
  filebrowser:
    image: gtst/filebrowser:beta
    container_name: filebrowser-quantum
    ports:
      - "8089:80"
    volumes:
      - /caminho/dos/seus/arquivos:/srv
      - ./data:/home/filebrowser/data
    restart: unless-stopped